package com.intranet.service.RMS;

import com.intranet.dto.rms.KPIStatDTO;
import com.intranet.dto.rms.RMSOrgSummaryResponseDTO;
import com.intranet.dto.rms.RMSProjectHoursDTO;
import com.intranet.entity.InternalProject;
import com.intranet.entity.TimeSheet;
import com.intranet.repository.InternalProjectRepo;
import com.intranet.repository.TimeSheetEntryRepo;
import com.intranet.repository.TimeSheetRepo;
import com.intranet.util.RMSCalculationUtils;
import com.intranet.util.cache.UserDirectoryService;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.DayOfWeek;
import java.time.LocalDate;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.stream.Collectors;

/**
 * Optimized service for org-level KPI aggregates only.
 * Executes a small number of aggregate DB queries — no per-resource loops.
 * Designed for fast initial dashboard rendering.
 */
@Service
@RequiredArgsConstructor
public class RMSSummaryService {

    private final TimeSheetRepo timeSheetRepository;
    private final TimeSheetEntryRepo entryRepository;
    private final InternalProjectRepo internalProjectRepo;
    private final UserDirectoryService userDirectoryService;

    public RMSOrgSummaryResponseDTO getOrgSummary(LocalDate startDate, LocalDate endDate, String authHeader) {

        // 1. Fetch user list from UMS (needed for totalUsers count)
        List<Map<String, Object>> users = userDirectoryService.fetchAllUsers2(authHeader);
        long totalUsers = users.stream().filter(u -> u.get("id") != null).count();

        // 2. Aggregate hour totals — 3 fast queries
        BigDecimal totalHours = RMSCalculationUtils.safe(
                timeSheetRepository.getTotalHoursForAllUsers(startDate, endDate));
        BigDecimal billableHours = RMSCalculationUtils.safe(
                entryRepository.getBillableHoursForAllUsers(startDate, endDate));
        BigDecimal nonBillableHours = RMSCalculationUtils.safe(
                entryRepository.getNonBillableHoursForAllUsers(startDate, endDate));

        // 3. Compute internal hours from project-level breakdown
        Set<Long> internalProjectIds = internalProjectRepo.findAll().stream()
                .map(InternalProject::getProjectId)
                .filter(pid -> pid != null)
                .map(Long::valueOf)
                .collect(Collectors.toSet());

        List<RMSProjectHoursDTO> projectHours = entryRepository.getProjectHoursForAllUsers(startDate, endDate);
        BigDecimal internalHours = projectHours.stream()
                .filter(p -> p.getProjectId() != null && internalProjectIds.contains(p.getProjectId()))
                .map(RMSProjectHoursDTO::getHours)
                .reduce(BigDecimal.ZERO, BigDecimal::add);
        BigDecimal otherNonBillableHours = nonBillableHours.subtract(internalHours)
                .max(BigDecimal.ZERO);

        // 4. Load timesheet headers only (no entries) for holidays + confidence score
        List<TimeSheet> timeSheets = timeSheetRepository.findByWorkDateBetween(startDate, endDate);

        Set<LocalDate> holidayDates = timeSheets.stream()
                .filter(ts -> Boolean.TRUE.equals(ts.getAutoGenerated()))
                .map(TimeSheet::getWorkDate)
                .collect(Collectors.toSet());

        long effectiveWorkingDays = 0;
        LocalDate cursor = startDate;
        while (!cursor.isAfter(endDate)) {
            boolean weekend = cursor.getDayOfWeek() == DayOfWeek.SATURDAY
                    || cursor.getDayOfWeek() == DayOfWeek.SUNDAY;
            if (!weekend && !holidayDates.contains(cursor)) effectiveWorkingDays++;
            cursor = cursor.plusDays(1);
        }

        BigDecimal plannedCapacity = BigDecimal.valueOf(effectiveWorkingDays * 8L * totalUsers);
        double utilization = RMSCalculationUtils.safePercentage(totalHours, plannedCapacity);
        double billableRatio = RMSCalculationUtils.safePercentage(billableHours, totalHours);
        int confidenceScore = timeSheets.isEmpty() ? 50
                : RMSCalculationUtils.calculateConfidenceScore(timeSheets);

        // 5. Averages
        BigDecimal avgDivisor = totalUsers > 0 ? BigDecimal.valueOf(totalUsers) : BigDecimal.ONE;
        BigDecimal avgTotal = totalHours.divide(avgDivisor, 2, RoundingMode.HALF_UP);
        BigDecimal avgBillable = billableHours.divide(avgDivisor, 2, RoundingMode.HALF_UP);
        BigDecimal avgNonBillable = nonBillableHours.divide(avgDivisor, 2, RoundingMode.HALF_UP);

        // 6. Percentage breakdown
        double billablePct = totalHours.compareTo(BigDecimal.ZERO) == 0 ? 0.0
                : billableHours.multiply(BigDecimal.valueOf(100))
                        .divide(totalHours, 2, RoundingMode.HALF_UP).doubleValue();
        double internalPct = totalHours.compareTo(BigDecimal.ZERO) == 0 ? 0.0
                : internalHours.multiply(BigDecimal.valueOf(100))
                        .divide(totalHours, 2, RoundingMode.HALF_UP).doubleValue();
        double otherNonBillablePct = totalHours.compareTo(BigDecimal.ZERO) == 0 ? 0.0
                : otherNonBillableHours.multiply(BigDecimal.valueOf(100))
                        .divide(totalHours, 2, RoundingMode.HALF_UP).doubleValue();

        // 7. KPI cards
        List<KPIStatDTO> kpiStats = List.of(
                KPIStatDTO.builder()
                        .label("Utilization")
                        .value(String.format("%.2f%%", utilization))
                        .trend(RMSCalculationUtils.calculateTrend(utilization))
                        .build(),
                KPIStatDTO.builder()
                        .label("Billable Ratio")
                        .value(String.format("%.2f%%", billableRatio))
                        .trend(RMSCalculationUtils.calculateTrend(billableRatio))
                        .build(),
                KPIStatDTO.builder()
                        .label("Confidence Score")
                        .value(String.format("%d%%", confidenceScore))
                        .trend(confidenceScore >= 75 ? "up" : "down")
                        .build()
        );

        return RMSOrgSummaryResponseDTO.builder()
                .startDate(startDate)
                .endDate(endDate)
                .totalHours(totalHours)
                .billableHours(billableHours)
                .nonBillableHours(nonBillableHours)
                .totalUsers(totalUsers)
                .totalResources(totalUsers)
                .utilization(RMSCalculationUtils.round(utilization))
                .billableRatio(RMSCalculationUtils.round(billableRatio))
                .confidenceScore(confidenceScore)
                .averageTotalHours(avgTotal)
                .averageBillableHours(avgBillable)
                .averageNonBillableHours(avgNonBillable)
                .billablePercentage(RMSCalculationUtils.round(billablePct))
                .internalNonBillablePercentage(RMSCalculationUtils.round(internalPct))
                .otherNonBillablePercentage(RMSCalculationUtils.round(otherNonBillablePct))
                .totalPercentage(100.0)
                .kpiStats(kpiStats)
                .build();
    }
}
