package com.intranet.service.utilization;

import com.intranet.dto.rms.RMSProjectHoursDTO;
import com.intranet.dto.rms.UtilizationSummaryDTO;
import com.intranet.entity.InternalProject;
import com.intranet.entity.TimeSheet;
import com.intranet.repository.InternalProjectRepo;
import com.intranet.repository.TimeSheetEntryRepo;
import com.intranet.repository.TimeSheetRepo;
import com.intranet.util.RMSCalculationUtils;
import com.intranet.util.UtilizationCalculationUtils;
import com.intranet.util.cache.UserDirectoryService;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.math.BigDecimal;
import java.time.DayOfWeek;
import java.time.LocalDate;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.stream.Collectors;

/**
 * Lightweight org-level utilization summary.
 * Executes only aggregate DB queries — no per-resource loops.
 * Optimized for the initial dashboard load.
 */
@Service
@RequiredArgsConstructor
@Slf4j
public class UtilizationSummaryService {

    private final TimeSheetRepo timeSheetRepository;
    private final TimeSheetEntryRepo entryRepository;
    private final InternalProjectRepo internalProjectRepo;
    private final UserDirectoryService userDirectoryService;

    public UtilizationSummaryDTO getSummary(LocalDate startDate, LocalDate endDate,
                                             boolean approvedOnly, String authHeader) {

        // 1. Fetch UMS users (for totalResources + totalRoles counts)
        List<Map<String, Object>> users = userDirectoryService.fetchAllUsers2(authHeader);
        int totalResources = (int) users.stream().filter(u -> u.get("id") != null).count();
        long distinctRoles = users.stream()
                .filter(u -> u.get("designation") != null)
                .map(u -> (String) u.get("designation"))
                .distinct().count();

        // 2. Aggregate hour queries (3 fast DB calls)
        BigDecimal totalHours = RMSCalculationUtils.safe(
                timeSheetRepository.getTotalHoursForAllUsers(startDate, endDate));
        BigDecimal billableHours = RMSCalculationUtils.safe(
                entryRepository.getBillableHoursForAllUsers(startDate, endDate));
        BigDecimal nonBillableRaw = RMSCalculationUtils.safe(
                entryRepository.getNonBillableHoursForAllUsers(startDate, endDate));

        // 3. Internal hours from project breakdown (1 DB call, filtered in memory)
        Set<Long> internalProjectIds = internalProjectRepo.findAll().stream()
                .map(InternalProject::getProjectId)
                .filter(pid -> pid != null)
                .map(Long::valueOf)
                .collect(Collectors.toSet());

        List<RMSProjectHoursDTO> projectBreakdown =
                entryRepository.getProjectHoursForAllUsers(startDate, endDate);

        BigDecimal internalHours = projectBreakdown.stream()
                .filter(p -> p.getProjectId() != null && internalProjectIds.contains(p.getProjectId()))
                .map(RMSProjectHoursDTO::getHours)
                .reduce(BigDecimal.ZERO, BigDecimal::add);

        BigDecimal nonBillableHours = nonBillableRaw.subtract(internalHours).max(BigDecimal.ZERO);
        int totalProjects = projectBreakdown.size();
        int totalClients = totalProjects; // no separate client table; use project count as proxy

        // 4. Load timesheet headers only (no entries) for holidays + confidence score
        List<TimeSheet> timeSheets = timeSheetRepository.findByWorkDateBetween(startDate, endDate);
        if (approvedOnly) {
            timeSheets = timeSheets.stream()
                    .filter(ts -> ts.getStatus() == TimeSheet.Status.APPROVED)
                    .collect(Collectors.toList());
        }

        // 5. Planned hours using holiday-aware working day count
        Set<LocalDate> holidayDates = timeSheets.stream()
                .filter(ts -> Boolean.TRUE.equals(ts.getAutoGenerated()))
                .map(TimeSheet::getWorkDate)
                .collect(Collectors.toSet());

        long effectiveWorkingDays = 0;
        LocalDate cursor = startDate;
        while (!cursor.isAfter(endDate)) {
            boolean weekend = cursor.getDayOfWeek() == DayOfWeek.SATURDAY
                    || cursor.getDayOfWeek() == DayOfWeek.SUNDAY;
            if (!weekend && !holidayDates.contains(cursor)) effectiveWorkingDays++;
            cursor = cursor.plusDays(1);
        }
        BigDecimal plannedHours = BigDecimal.valueOf(effectiveWorkingDays * 8L * totalResources);

        // 6. Derived metrics
        BigDecimal utilizationPct = UtilizationCalculationUtils
                .calculateUtilizationPercentage(totalHours, plannedHours);

        int rawConfidence = timeSheets.isEmpty() ? 50
                : UtilizationCalculationUtils.calculateConfidenceScore(timeSheets);
        BigDecimal confidenceScore = BigDecimal.valueOf(rawConfidence);

        log.info("UtilizationSummaryService: totalHours={}, planned={}, util={}%, resources={}",
                totalHours, plannedHours, utilizationPct, totalResources);

        return UtilizationSummaryDTO.builder()
                .startDate(startDate)
                .endDate(endDate)
                .totalHours(totalHours)
                .plannedHours(plannedHours)
                .utilizationPercentage(utilizationPct)
                .billableHours(billableHours)
                .nonBillableHours(nonBillableHours)
                .internalHours(internalHours)
                .totalResources(totalResources)
                .totalProjects(totalProjects)
                .totalClients(totalClients)
                .totalRoles((int) distinctRoles)
                .confidenceScore(confidenceScore)
                .approvedDataOnly(approvedOnly)
                .build();
    }
}
