package com.intranet.repository;

import com.intranet.service.TimeUtil;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;
import java.util.Optional;
import java.util.Set;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;


import com.intranet.entity.TimeSheet;

@Repository
public interface TimeSheetRepo extends JpaRepository<TimeSheet, Long> {
     Optional<TimeSheet> findByUserIdAndWorkDate(Long userId, LocalDate workDate);

     List<TimeSheet> findByUserIdAndWeekInfo_IdInOrderByWorkDateAsc(Long userId, List<Long> weekIds);

     List<TimeSheet> findByWorkDateBetween(LocalDate startDate, LocalDate endDate);

     @Query("SELECT ts FROM TimeSheet ts LEFT JOIN FETCH ts.weekInfo LEFT JOIN FETCH ts.entries WHERE ts.workDate BETWEEN :startDate AND :endDate")
     List<TimeSheet> findByWorkDateBetweenWithWeekInfoAndEntries(@Param("startDate") LocalDate startDate, @Param("endDate") LocalDate endDate);

     @Query("SELECT t FROM TimeSheet t " +
       "JOIN FETCH t.weekInfo w " +
       "WHERE t.userId IN :userIds AND t.status = 'SUBMITTED'")
     List<TimeSheet> findSubmittedByUserIds(@Param("userIds") Set<Long> userIds);

     List<TimeSheet> findByUserIdAndWeekInfo_Id(Long userId, Long weekInfoId);

     @Query("SELECT ts FROM TimeSheet ts WHERE ts.userId IN :userIds AND ts.status <> 'DRAFT'")
    List<TimeSheet> findNonDraftByUserIds(@Param("userIds") Set<Long> userIds);

     List<TimeSheet> findByUserIdAndWorkDateBetween(Long userId, LocalDate startOfMonth, LocalDate endOfMonth);

     List<TimeSheet> findByUserIdInAndWorkDateBetween(Set<Long> memberIds, LocalDate startDate, LocalDate endDate);

     boolean existsByUserIdAndWorkDate(Long userId, LocalDate date);

      // Fetch all timesheets except DRAFT
     @Query("SELECT t FROM TimeSheet t WHERE t.status <> com.intranet.entity.TimeSheet.Status.DRAFT")
    List<TimeSheet> findAllNonDraft();

    @Query("SELECT DISTINCT t " +
       "FROM TimeSheet t " +
       "LEFT JOIN FETCH t.entries e " +
       "WHERE t.status <> com.intranet.entity.TimeSheet.Status.DRAFT")
    List<TimeSheet> findAllNonDraftWithEntries();

    boolean existsByUserIdAndWorkDateAndAutoGeneratedTrue(Long userId, LocalDate holidayDate);

    List<TimeSheet> findByUserId(Long userId);

    @Query("SELECT DISTINCT ts FROM TimeSheet ts LEFT JOIN FETCH ts.entries WHERE ts.userId = :userId AND ts.workDate BETWEEN :startDate AND :endDate")
    List<TimeSheet> findByUserIdAndWorkDateBetweenWithEntries(@Param("userId") Long userId,
                                                              @Param("startDate") LocalDate startDate,
                                                              @Param("endDate") LocalDate endDate);

    /*
     * HH.MM literals cannot be summed with SQL SUM(): 0.30 + 0.30 gives 0.60 where the answer
     * is 1.00. These queries sum MINUTES instead - exact, because the column is DECIMAL - and
     * the default methods convert back to HH.MM so callers are unchanged.
     */
    @Query("SELECT COALESCE(SUM(FLOOR(t.hoursWorked) * 60 + (t.hoursWorked - FLOOR(t.hoursWorked)) * 100), 0) " +
           "FROM TimeSheet t " +
           "WHERE t.workDate BETWEEN :startDate AND :endDate")
    BigDecimal getTotalMinutesForAllUsers(LocalDate startDate, LocalDate endDate);

    /** Total as an HH.MM literal; the query above sums minutes. */
    default BigDecimal getTotalHoursForAllUsers(LocalDate startDate, LocalDate endDate) {
        return TimeUtil.minutesResultToHHMM(getTotalMinutesForAllUsers(startDate, endDate));
    }

    @Query("SELECT COUNT(DISTINCT t.userId) " +
           "FROM TimeSheet t " +
           "WHERE t.workDate BETWEEN :startDate AND :endDate")
    Long getUniqueUserCount(LocalDate startDate, LocalDate endDate);

    @Query("SELECT DAYNAME(t.workDate), COALESCE(SUM(FLOOR(t.hoursWorked) * 60 + (t.hoursWorked - FLOOR(t.hoursWorked)) * 100), 0) " +
           "FROM TimeSheet t " +
           "WHERE t.workDate BETWEEN :startDate AND :endDate " +
           "GROUP BY DAYNAME(t.workDate), t.workDate " +
           "ORDER BY t.workDate")
    List<Object[]> getDailyMinutesBreakdown(LocalDate startDate, LocalDate endDate);

    /** [label, HH.MM hours]; the query above sums minutes. */
    default List<Object[]> getDailyHoursBreakdown(LocalDate startDate, LocalDate endDate) {
        List<Object[]> rows = getDailyMinutesBreakdown(startDate, endDate);
        rows.forEach(r -> r[1] = TimeUtil.minutesResultToHHMM(r[1]));
        return rows;
    }

    @Query("SELECT CONCAT('Week ', WEEK(t.workDate)), COALESCE(SUM(FLOOR(t.hoursWorked) * 60 + (t.hoursWorked - FLOOR(t.hoursWorked)) * 100), 0) " +
           "FROM TimeSheet t " +
           "WHERE t.workDate BETWEEN :startDate AND :endDate " +
           "GROUP BY WEEK(t.workDate), YEAR(t.workDate), CONCAT('Week ', WEEK(t.workDate)) " +
           "ORDER BY WEEK(t.workDate)")
    List<Object[]> getWeeklyMinutesBreakdown(LocalDate startDate, LocalDate endDate);

    /** [label, HH.MM hours]; the query above sums minutes. */
    default List<Object[]> getWeeklyHoursBreakdown(LocalDate startDate, LocalDate endDate) {
        List<Object[]> rows = getWeeklyMinutesBreakdown(startDate, endDate);
        rows.forEach(r -> r[1] = TimeUtil.minutesResultToHHMM(r[1]));
        return rows;
    }

    @Query("SELECT MONTHNAME(t.workDate), COALESCE(SUM(FLOOR(t.hoursWorked) * 60 + (t.hoursWorked - FLOOR(t.hoursWorked)) * 100), 0) " +
           "FROM TimeSheet t " +
           "WHERE t.workDate BETWEEN :startDate AND :endDate " +
           "GROUP BY MONTH(t.workDate), YEAR(t.workDate), MONTHNAME(t.workDate) " +
           "ORDER BY YEAR(t.workDate), MONTH(t.workDate)")
    List<Object[]> getMonthlyMinutesBreakdown(LocalDate startDate, LocalDate endDate);

    /** [label, HH.MM hours]; the query above sums minutes. */
    default List<Object[]> getMonthlyHoursBreakdown(LocalDate startDate, LocalDate endDate) {
        List<Object[]> rows = getMonthlyMinutesBreakdown(startDate, endDate);
        rows.forEach(r -> r[1] = TimeUtil.minutesResultToHHMM(r[1]));
        return rows;
    }

}
