package com.intranet.service;

import com.intranet.entity.*;
import com.intranet.dto.UserHoursDTO;
import com.intranet.repository.TimeSheetRepo;
import com.intranet.repository.WeekInfoRepo;
import com.intranet.repository.WeeklyTimeSheetReviewRepo;

import jakarta.servlet.http.HttpServletRequest;
import lombok.RequiredArgsConstructor;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.core.ParameterizedTypeReference;
import org.springframework.http.*;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;
import org.springframework.web.context.request.RequestContextHolder;
import org.springframework.web.context.request.ServletRequestAttributes;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.*;
import java.util.*;
import java.util.stream.Collectors;

@Service
@RequiredArgsConstructor
public class DashboardService {

    private final TimeSheetRepo timeSheetRepo;
    private final WeeklyTimeSheetReviewRepo weeklyReviewRepo;
    private final WeekInfoRepo weekInfoRepo;
    private final RestTemplate restTemplate = new RestTemplate();

    @Value("${pms.api.base-url}")
    private String pmsBaseUrl;

    // 🧩 Build Auth Headers
    private HttpEntity<Void> buildEntityWithAuth() {
        ServletRequestAttributes attrs = (ServletRequestAttributes) RequestContextHolder.getRequestAttributes();
        HttpHeaders headers = new HttpHeaders();
        if (attrs != null) {
            HttpServletRequest request = attrs.getRequest();
            String token = request.getHeader("Authorization");
            if (token != null && !token.isBlank()) headers.set("Authorization", token);
        }
        return new HttpEntity<>(headers);
    }

    // 🧾 MAIN SERVICE METHOD
    public Map<String, Object> getDashboardSummary(Long userId, LocalDate startDate, LocalDate endDate) {

        LocalDate today = LocalDate.now();
        if (startDate == null) startDate = today.withDayOfMonth(1);
        if (endDate == null) endDate = today;

        // 1️⃣ Fetch PMS Project Names
        Map<Long, String> projectMap = fetchProjectMap();

        // 2️⃣ Fetch Timesheets
        List<TimeSheet> timeSheets = timeSheetRepo.findByUserIdAndWorkDateBetween(userId, startDate, endDate);
        List<TimeSheetEntry> entries = timeSheets.stream()
                .flatMap(ts -> ts.getEntries().stream())
                .collect(Collectors.toList());

        // 3️⃣ Weekly Review Summary using WeekInfo + WeekTimeSheetReview
        Map<String, Object> weeklyTimesheetReview = getWeeklySummary(userId, startDate, endDate);

        // 4️⃣ Billable Activity
        Map<String, Object> billableActivity = calculateBillableActivity(entries, timeSheets);

        // 5️⃣ Project Summary
        List<Map<String, Object>> projectSummary = calculateProjectSummary(entries, projectMap);

        // 6️⃣ Weekly Summary (Mon–Sun)
        Map<String, BigDecimal> weeklySummary = calculateWeeklySummary(entries, timeSheets);

        // 7️⃣ Productivity Details
        Map<String, Object> billablePercentageDetails = calculateBillablePercentageDetails(entries);

        // ✅ Total hours. Hours are HH.MM literals (8.30 = 8h30m), so they MUST be summed
        // through TimeUtil, which converts to minutes first. Plain BigDecimal.add read .30 as
        // three-tenths of an hour and silently under-reported every carry by 40 minutes -
        // four 8-hour days came out as 30 hrs instead of 32.
        // computeTimeSheetHours picks the right source per day: stored hours for an
        // auto-generated day (it has no entries), recomputed from raw times otherwise.
        BigDecimal totalHours = TimeUtil.sumHours(
                timeSheets.stream()
                        .map(TimeUtil::computeTimeSheetHours)
                        .collect(Collectors.toList()));


        // 🕒 Step 1: Count only *manual* (non-auto-generated) timesheets with actual entries
        long totalWorkedDays = timeSheets.stream()
                .filter(ts -> !Boolean.TRUE.equals(ts.getAutoGenerated())) // exclude auto-generated
                .filter(ts -> ts.getEntries() != null && !ts.getEntries().isEmpty()) // exclude empty timesheets
                .map(TimeSheet::getWorkDate)
                .distinct()
                .count();

        // 🕒 Step 2: Use existing totalHours (which includes auto-generated) for display
        String avgHoursPerDay = calculateAverageHoursPerDay(totalHours, totalWorkedDays);


        // 🧾 Final Aggregated Response
        return Map.of(
                "weeklyTimesheetReview", weeklyTimesheetReview,
                "billableActivity", billableActivity,
                "projectSummary", projectSummary,
                "weeklySummary", weeklySummary,
                "billablePercentageDetails", billablePercentageDetails,
                "totalHours", totalHours,
                "averageHoursPerDay", avgHoursPerDay,
                "dateRange", Map.of("startDate", startDate, "endDate", endDate)
        );
    }

    // ✅ Fetch Project Map
    private Map<Long, String> fetchProjectMap() {
        try {
            ResponseEntity<List<Map<String, Object>>> resp = restTemplate.exchange(
                    pmsBaseUrl + "/projects/tms",
                    HttpMethod.GET,
                    buildEntityWithAuth(),
                    new ParameterizedTypeReference<List<Map<String, Object>>>() {}
            );
            if (resp.getBody() == null) return new HashMap<>();

            return resp.getBody().stream()
                    .collect(Collectors.toMap(
                            p -> ((Number) p.get("id")).longValue(),
                            p -> (String) p.get("name"),
                            (a, b) -> a
                    ));
        } catch (Exception e) {
            return new HashMap<>();
        }
    }

        private Map<String, Object> calculateBillableActivity(List<TimeSheetEntry> entries, List<TimeSheet> timeSheets) {
        // ✅ Step 1: Compute total billable and non-billable hours from entries
        BigDecimal billableHours = TimeUtil.sumEntryHours(
                entries.stream().filter(TimeSheetEntry::isBillable).collect(Collectors.toList()));

        BigDecimal nonBillableHoursFromEntries = TimeUtil.sumEntryHours(
                entries.stream().filter(e -> !e.isBillable()).collect(Collectors.toList()));

        // ✅ Step 2: Add auto-generated timesheets as non-billable hours
        BigDecimal autoGeneratedHours = TimeUtil.sumHours(
                timeSheets.stream()
                        .filter(ts -> Boolean.TRUE.equals(ts.getAutoGenerated()))
                        .map(ts -> ts.getHoursWorked() != null ? ts.getHoursWorked() : BigDecimal.ZERO)
                        .collect(Collectors.toList()));

        BigDecimal totalNonBillableHours =
                TimeUtil.sumHours(List.of(nonBillableHoursFromEntries, autoGeneratedHours));

        // ✅ Step 3: Calculate totals and percentages
        BigDecimal totalHours = TimeUtil.sumHours(List.of(billableHours, totalNonBillableHours));

        // The ratio has to be taken in minutes too: dividing HH.MM literals directly treats
        // 7.30 as 7.3 and skews the percentage.
        long billableMinutes = TimeUtil.hhmmToMinutes(billableHours);
        long totalMinutes = TimeUtil.hhmmToMinutes(totalHours);
        double billablePercentage = totalMinutes == 0
                ? 0.0
                : BigDecimal.valueOf(billableMinutes * 100.0 / totalMinutes)
                        .setScale(2, java.math.RoundingMode.HALF_UP)
                        .doubleValue();

        // ✅ Step 4: Build clean response
        return Map.of(
                "billableHours", billableHours,
                "nonBillableHours", totalNonBillableHours,
                "billablePercentage", billablePercentage
        );
        }


    // ✅ Project Summary
    private List<Map<String, Object>> calculateProjectSummary(List<TimeSheetEntry> entries, Map<Long, String> projectMap) {
    // Group the entries, then let TimeUtil sum each group in minutes.
    Map<Long, BigDecimal> projectHours = entries.stream()
            .filter(e -> e.getProjectId() != null) // ignore missing project entries
            .collect(Collectors.groupingBy(
                    TimeSheetEntry::getProjectId,
                    Collectors.collectingAndThen(Collectors.toList(), TimeUtil::sumEntryHours)
            ));

    return projectHours.entrySet().stream().map(e -> {
        Map<String, Object> m = new HashMap<>();
        m.put("projectId", e.getKey());
        m.put("projectName", projectMap.getOrDefault(e.getKey(), "Unknown Project"));
        m.put("totalHoursWorked", e.getValue());
        return m;
    }).collect(Collectors.toList());
    }


    // ✅ Weekly Summary (hours by weekday)
        private Map<String, BigDecimal> calculateWeeklySummary(List<TimeSheetEntry> entries, List<TimeSheet> timeSheets) {
        // ✅ Step 1: Initialize map for all weekdays (Mon–Sun)
        Map<String, BigDecimal> weeklySummary = Arrays.stream(DayOfWeek.values())
                .collect(Collectors.toMap(
                        d -> d.name().toLowerCase(),
                        d -> BigDecimal.ZERO,
                        (a, b) -> a,
                        LinkedHashMap::new
                ));

        // ✅ Step 2+3: Accumulate in MINUTES per weekday, then convert once at the end.
        // Adding HH.MM literals together directly is what lost 40 minutes on every carry.
        Map<String, Long> minutesPerDay = new LinkedHashMap<>();

        for (TimeSheetEntry entry : entries) {
                if (entry == null || entry.getTimeSheet() == null || entry.getTimeSheet().getWorkDate() == null)
                continue;

                LocalDate workDate = entry.getTimeSheet().getWorkDate();
                String dayKey = workDate.getDayOfWeek().name().toLowerCase();
                minutesPerDay.merge(dayKey, TimeUtil.hhmmToMinutes(TimeUtil.sumEntryHours(List.of(entry))), Long::sum);
        }

        for (TimeSheet ts : timeSheets) {
                if (Boolean.TRUE.equals(ts.getAutoGenerated()) && ts.getWorkDate() != null) {
                String dayKey = ts.getWorkDate().getDayOfWeek().name().toLowerCase();
                BigDecimal hours = ts.getHoursWorked() != null ? ts.getHoursWorked() : BigDecimal.ZERO;
                minutesPerDay.merge(dayKey, TimeUtil.hhmmToMinutes(hours), Long::sum);
                }
        }

        // ✅ Step 4: Convert each weekday's minutes back to the HH.MM literal
        weeklySummary.replaceAll((k, v) -> TimeUtil.minutesToHHMM(minutesPerDay.getOrDefault(k, 0L)));

        return weeklySummary;
        }


    // ✅ Productivity Details (by day)
    private Map<String, Object> calculateBillablePercentageDetails(List<TimeSheetEntry> entries) {
        // 1️⃣ Group entries by day of week
    Map<DayOfWeek, List<TimeSheetEntry>> dayWise = entries.stream()
            .filter(e -> e.getTimeSheet() != null && e.getTimeSheet().getWorkDate() != null)
            .collect(Collectors.groupingBy(
                    e -> e.getTimeSheet().getWorkDate().getDayOfWeek(),
                    LinkedHashMap::new,
                    Collectors.toList()
            ));

    // 2️⃣ Total billable hours across all days
    BigDecimal totalBillable = TimeUtil.sumEntryHours(
            entries.stream().filter(TimeSheetEntry::isBillable).collect(Collectors.toList()));

    // If no billable hours → all productivity = 0
    if (totalBillable.compareTo(BigDecimal.ZERO) == 0) {
        Map<String, Object> empty = new LinkedHashMap<>();
        for (DayOfWeek day : DayOfWeek.values()) {
            empty.put(day.name().toLowerCase(), Map.of(
                    "billableHours", BigDecimal.ZERO,
                    "billablePercentage", 0.0
            ));
        }
        return empty;
    }

    // 3️⃣ Build per-day productivity
    Map<String, Object> productivity = new LinkedHashMap<>();

    for (DayOfWeek day : DayOfWeek.values()) {

        List<TimeSheetEntry> dayEntries = dayWise.getOrDefault(day, new ArrayList<>());

        BigDecimal dayBillable = TimeUtil.sumEntryHours(
                dayEntries.stream().filter(TimeSheetEntry::isBillable).collect(Collectors.toList()));

        // Productivity = (dayBillable / totalBillable) * 100, taken in minutes so a
        // half hour counts as 30 minutes and not as three tenths of an hour.
        BigDecimal pct = BigDecimal.ZERO;
        long dayBillableMinutes = TimeUtil.hhmmToMinutes(dayBillable);
        long totalBillableMinutes = TimeUtil.hhmmToMinutes(totalBillable);
        if (dayBillableMinutes > 0 && totalBillableMinutes > 0) {
            pct = BigDecimal.valueOf(dayBillableMinutes * 100.0 / totalBillableMinutes)
                    .setScale(2, RoundingMode.HALF_UP);
        }

        productivity.put(day.name().toLowerCase(), Map.of(
                "billableHours", dayBillable,
                "billablePercentage", pct.doubleValue() // ← numeric, NOT string
        ));
    }

    return productivity;
        
 }



    // ✅ Week-based Review Summary (using WeekInfo & WeekTimeSheetReview)
    public Map<String, Object> getWeeklySummary(Long userId, LocalDate startDate, LocalDate endDate) {

    // 1️⃣ Fetch all week ranges between start and end date
    List<WeekInfo> allWeeks = weekInfoRepo.findByStartDateBetween(startDate, endDate);

    // 2️⃣ Fetch only the existing weekly reviews for this user
    List<WeeklyTimeSheetReview> reviews =
            weeklyReviewRepo.findByUserIdAndWeekInfo_StartDateBetween(userId, startDate, endDate);

    // 3️⃣ Map weekId → list of statuses
    Map<Long, List<WeeklyTimeSheetReview.Status>> reviewMap = reviews.stream()
            .collect(Collectors.groupingBy(
                    r -> r.getWeekInfo().getId(),
                    Collectors.mapping(WeeklyTimeSheetReview::getStatus, Collectors.toList())
            ));

    long submitted = 0, approved = 0, rejected = 0, notSubmitted = 0;

    // 4️⃣ Loop through all week infos (including those without reviews)
    for (WeekInfo week : allWeeks) {
        List<WeeklyTimeSheetReview.Status> statuses = reviewMap.get(week.getId());

        if (statuses == null || statuses.isEmpty()) {
            notSubmitted++;
        } else if (statuses.contains(WeeklyTimeSheetReview.Status.REJECTED)) {
            rejected++;
        } else if (statuses.stream().allMatch(s -> s == WeeklyTimeSheetReview.Status.APPROVED)) {
            approved++;
        } else {
            submitted++;
        }
    }

    // 5️⃣ Return only summary counts
    return Map.of(
            "submittedWeeks", submitted,
            "approvedWeeks", approved,
            "rejectedWeeks", rejected,
            "notSubmittedWeeks", notSubmitted
    );
    }


    // ✅ Utility Helpers
    // formatHours() was removed: it only ever carried minutes once, so it could not repair
    // a fraction that plain BigDecimal.add had already over-accumulated. All sums now go
    // through TimeUtil, which returns a normalised HH.MM literal.
    private String calculateAverageHoursPerDay(BigDecimal totalHours, long totalDays) {
        if (totalDays == 0 || totalHours.compareTo(BigDecimal.ZERO) <= 0) return "00:00";
        long totalMinutes = TimeUtil.hhmmToMinutes(totalHours);
        long avgMinutes = totalMinutes / totalDays;
        return String.format("%02d:%02d", avgMinutes / 60, avgMinutes % 60);
    }

    public List<UserHoursDTO> getUsersHoursSummary(List<Long> userIds, LocalDate startDate, LocalDate endDate) {
        System.out.println("DEBUG: getUsersHoursSummary called with " + userIds.size() + " user IDs");
        System.out.println("DEBUG: Date range: " + startDate + " to " + endDate);
        
        return userIds.stream()
                .map(userId -> {
                    // Fetch timesheets for this user in the date range
                    List<TimeSheet> timeSheets = timeSheetRepo.findByUserIdAndWorkDateBetween(userId, startDate, endDate);
                    List<TimeSheetEntry> entries = timeSheets.stream()
                            .flatMap(ts -> ts.getEntries().stream())
                            .collect(Collectors.toList());

                    // Calculate billable and non-billable hours
                    // HH.MM literals must be summed in minutes (TimeUtil), never with
                    // BigDecimal.add - see the note on the grand total above.
                    BigDecimal billableHours = TimeUtil.sumEntryHours(
                            entries.stream().filter(TimeSheetEntry::isBillable).collect(Collectors.toList()));

                    BigDecimal nonBillableHoursFromEntries = TimeUtil.sumEntryHours(
                            entries.stream().filter(e -> !e.isBillable()).collect(Collectors.toList()));

                    // Add auto-generated timesheets as non-billable hours
                    BigDecimal autoGeneratedHours = TimeUtil.sumHours(
                            timeSheets.stream()
                                    .filter(ts -> Boolean.TRUE.equals(ts.getAutoGenerated()))
                                    .map(ts -> ts.getHoursWorked() != null ? ts.getHoursWorked() : BigDecimal.ZERO)
                                    .collect(Collectors.toList()));

                    BigDecimal totalNonBillableHours =
                            TimeUtil.sumHours(List.of(nonBillableHoursFromEntries, autoGeneratedHours));
                    BigDecimal totalHours =
                            TimeUtil.sumHours(List.of(billableHours, totalNonBillableHours));

                    // Calculate billable percentage in minutes
                    long billableMinutes = TimeUtil.hhmmToMinutes(billableHours);
                    long totalMinutes = TimeUtil.hhmmToMinutes(totalHours);
                    double billablePercentage = totalMinutes == 0
                            ? 0.0
                            : BigDecimal.valueOf(billableMinutes * 100.0 / totalMinutes)
                                    .setScale(2, RoundingMode.HALF_UP)
                                    .doubleValue();

                    UserHoursDTO userHours = new UserHoursDTO();
                    userHours.setUserId(userId);
                    userHours.setBillableHours(billableHours);
                    userHours.setNonBillableHours(totalNonBillableHours);
//                    userHours.setTotalHours(totalHours);
                    userHours.setBillablePercentage(billablePercentage);

                    return userHours;
                })
                .collect(Collectors.toList());
    }

    private double round(double value, int places) {
        return Math.round(value * Math.pow(10, places)) / Math.pow(10, places);
    }
}
