package com.intranet.util;

import com.intranet.dto.rms.AlertDTO;
import com.intranet.dto.rms.PortfolioTrendDTO;
import com.intranet.entity.TimeSheet;
import com.intranet.entity.TimeSheetEntry;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.DayOfWeek;
import java.time.LocalDate;
import java.time.YearMonth;
import java.util.*;
import java.util.function.Predicate;
import java.util.stream.Collectors;

public final class RMSCalculationUtils {

    private RMSCalculationUtils() {}

    public static BigDecimal safe(BigDecimal value) {
        return value == null ? BigDecimal.ZERO : value;
    }

    public static double safePercentage(BigDecimal actual, BigDecimal planned) {
        if (planned == null || planned.compareTo(BigDecimal.ZERO) == 0) return 0.0;
        return actual.multiply(BigDecimal.valueOf(100))
                .divide(planned, 2, RoundingMode.HALF_UP)
                .doubleValue();
    }

    public static double round(double value) {
        return BigDecimal.valueOf(value).setScale(2, RoundingMode.HALF_UP).doubleValue();
    }

    public static String calculateTrend(double value) {
        if (value >= 80) return "up";
        if (value >= 50) return "flat";
        return "down";
    }

    public static long calculateWorkingDays(LocalDate startDate, LocalDate endDate) {
        long workingDays = 0;
        LocalDate current = startDate;
        while (!current.isAfter(endDate)) {
            int dow = current.getDayOfWeek().getValue();
            if (dow <= 5) workingDays++;
            current = current.plusDays(1);
        }
        return workingDays;
    }

    public static int calculateConfidenceScore(List<TimeSheet> timeSheets) {
        BigDecimal approved = timeSheets.stream()
                .filter(ts -> ts.getStatus() == TimeSheet.Status.APPROVED)
                .map(ts -> safe(ts.getHoursWorked()))
                .reduce(BigDecimal.ZERO, BigDecimal::add);
        BigDecimal draft = timeSheets.stream()
                .filter(ts -> ts.getStatus() == TimeSheet.Status.DRAFT)
                .map(ts -> safe(ts.getHoursWorked()))
                .reduce(BigDecimal.ZERO, BigDecimal::add);
        BigDecimal total = approved.add(draft);
        if (total.compareTo(BigDecimal.ZERO) == 0) return 50;
        return approved.multiply(BigDecimal.valueOf(100))
                .divide(total, 0, RoundingMode.HALF_UP)
                .intValue();
    }

    public static BigDecimal sumEntryHours(List<TimeSheetEntry> entries, Predicate<TimeSheetEntry> predicate) {
        return entries.stream()
                .filter(predicate)
                .map(e -> safe(e.getHoursWorked()))
                .reduce(BigDecimal.ZERO, BigDecimal::add);
    }

    public static Map<LocalDate, BigDecimal> buildActualByDate(List<TimeSheetEntry> entries) {
        return entries.stream()
                .filter(e -> e.getTimeSheet() != null && e.getTimeSheet().getWorkDate() != null)
                .collect(Collectors.groupingBy(
                        e -> e.getTimeSheet().getWorkDate(),
                        Collectors.mapping(
                                e -> safe(e.getHoursWorked()),
                                Collectors.reducing(BigDecimal.ZERO, BigDecimal::add)
                        )
                ));
    }

    public static Map<LocalDate, Integer> buildPlannedByDate(LocalDate startDate, LocalDate endDate,
                                                              List<TimeSheet> timeSheets) {
        Set<LocalDate> holidayDates = timeSheets.stream()
                .filter(ts -> Boolean.TRUE.equals(ts.getAutoGenerated()))
                .map(TimeSheet::getWorkDate)
                .collect(Collectors.toSet());

        Map<LocalDate, Integer> planned = new LinkedHashMap<>();
        LocalDate cursor = startDate;
        while (!cursor.isAfter(endDate)) {
            boolean weekend = cursor.getDayOfWeek() == DayOfWeek.SATURDAY
                    || cursor.getDayOfWeek() == DayOfWeek.SUNDAY;
            planned.put(cursor, (!weekend && !holidayDates.contains(cursor)) ? 8 : 0);
            cursor = cursor.plusDays(1);
        }
        return planned;
    }

    public static List<PortfolioTrendDTO> buildDailyTrends(LocalDate startDate, LocalDate endDate,
                                                            Map<LocalDate, BigDecimal> actualByDate,
                                                            Map<LocalDate, Integer> plannedByDate) {
        List<PortfolioTrendDTO> trends = new ArrayList<>();
        LocalDate cursor = startDate;
        while (!cursor.isAfter(endDate)) {
            BigDecimal actual = actualByDate.getOrDefault(cursor, BigDecimal.ZERO);
            BigDecimal planned = BigDecimal.valueOf(plannedByDate.getOrDefault(cursor, 0));
            trends.add(PortfolioTrendDTO.builder()
                    .period(cursor.toString())
                    .actual(actual.intValue())
                    .planned(planned.intValue())
                    .util(round(safePercentage(actual, planned)))
                    .build());
            cursor = cursor.plusDays(1);
        }
        return trends;
    }

    public static List<PortfolioTrendDTO> buildWeeklyTrends(LocalDate startDate, LocalDate endDate,
                                                             Map<LocalDate, BigDecimal> actualByDate,
                                                             Map<LocalDate, Integer> plannedByDate) {
        Map<LocalDate, BigDecimal> actualByWeek = new LinkedHashMap<>();
        Map<LocalDate, BigDecimal> plannedByWeek = new LinkedHashMap<>();
        LocalDate cursor = startDate;
        while (!cursor.isAfter(endDate)) {
            LocalDate weekKey = cursor.with(DayOfWeek.MONDAY);
            actualByWeek.merge(weekKey, actualByDate.getOrDefault(cursor, BigDecimal.ZERO), BigDecimal::add);
            plannedByWeek.merge(weekKey,
                    BigDecimal.valueOf(plannedByDate.getOrDefault(cursor, 0)), BigDecimal::add);
            cursor = cursor.plusDays(1);
        }
        return actualByWeek.entrySet().stream()
                .sorted(Map.Entry.comparingByKey())
                .map(entry -> {
                    BigDecimal actual = entry.getValue();
                    BigDecimal planned = plannedByWeek.getOrDefault(entry.getKey(), BigDecimal.ZERO);
                    return PortfolioTrendDTO.builder()
                            .period(String.format("Wk of %s", entry.getKey()))
                            .actual(actual.intValue())
                            .planned(planned.intValue())
                            .util(round(safePercentage(actual, planned)))
                            .build();
                })
                .collect(Collectors.toList());
    }

    public static List<PortfolioTrendDTO> buildMonthlyTrends(LocalDate startDate, LocalDate endDate,
                                                              Map<LocalDate, BigDecimal> actualByDate,
                                                              Map<LocalDate, Integer> plannedByDate) {
        Map<YearMonth, BigDecimal> actualByMonth = new LinkedHashMap<>();
        Map<YearMonth, BigDecimal> plannedByMonth = new LinkedHashMap<>();
        LocalDate cursor = startDate;
        while (!cursor.isAfter(endDate)) {
            YearMonth monthKey = YearMonth.from(cursor);
            actualByMonth.merge(monthKey, actualByDate.getOrDefault(cursor, BigDecimal.ZERO), BigDecimal::add);
            plannedByMonth.merge(monthKey,
                    BigDecimal.valueOf(plannedByDate.getOrDefault(cursor, 0)), BigDecimal::add);
            cursor = cursor.plusDays(1);
        }
        return actualByMonth.entrySet().stream()
                .sorted(Map.Entry.comparingByKey())
                .map(entry -> {
                    BigDecimal actual = entry.getValue();
                    BigDecimal planned = plannedByMonth.getOrDefault(entry.getKey(), BigDecimal.ZERO);
                    return PortfolioTrendDTO.builder()
                            .period(entry.getKey().getMonth().name() + " " + entry.getKey().getYear())
                            .actual(actual.intValue())
                            .planned(planned.intValue())
                            .util(round(safePercentage(actual, planned)))
                            .build();
                })
                .collect(Collectors.toList());
    }

    public static List<AlertDTO> buildAlerts(LocalDate startDate, LocalDate endDate,
                                              Map<LocalDate, BigDecimal> actualByDate,
                                              Map<LocalDate, Integer> plannedByDate,
                                              double utilizationPercentage,
                                              int confidenceScore) {
        List<AlertDTO> alerts = new ArrayList<>();
        if (hasFourConsecutiveCriticalWeeks(startDate, endDate, actualByDate, plannedByDate)) {
            alerts.add(AlertDTO.builder()
                    .id("rms-breach-1").scope("weekly")
                    .message("Detected 4 consecutive critical weeks with under-performance.")
                    .severity("high").status("open").build());
        }
        if (utilizationPercentage < 60) {
            alerts.add(AlertDTO.builder()
                    .id("rms-utilization-low").scope("resource")
                    .message("Overall utilization is below 60%, red zone for the business.")
                    .severity("medium").status("open").build());
        }
        if (confidenceScore < 50) {
            alerts.add(AlertDTO.builder()
                    .id("rms-confidence-low").scope("approval")
                    .message("Low confidence due to draft timesheets in the selected period.")
                    .severity("medium").status("open").build());
        }
        return alerts;
    }

    private static boolean hasFourConsecutiveCriticalWeeks(LocalDate startDate, LocalDate endDate,
                                                            Map<LocalDate, BigDecimal> actualByDate,
                                                            Map<LocalDate, Integer> plannedByDate) {
        List<LocalDate> orderedWeeks = buildWeeklyKeys(startDate, endDate);
        int consecutive = 0;
        for (LocalDate weekStart : orderedWeeks) {
            BigDecimal actual = actualByDate.entrySet().stream()
                    .filter(e -> weekStart.equals(e.getKey().with(DayOfWeek.MONDAY)))
                    .map(Map.Entry::getValue).reduce(BigDecimal.ZERO, BigDecimal::add);
            BigDecimal planned = plannedByDate.entrySet().stream()
                    .filter(e -> weekStart.equals(e.getKey().with(DayOfWeek.MONDAY)))
                    .map(e -> BigDecimal.valueOf(e.getValue())).reduce(BigDecimal.ZERO, BigDecimal::add);
            if (safePercentage(actual, planned) < 70) {
                if (++consecutive >= 4) return true;
            } else {
                consecutive = 0;
            }
        }
        return false;
    }

    private static List<LocalDate> buildWeeklyKeys(LocalDate startDate, LocalDate endDate) {
        Map<LocalDate, Boolean> weekMap = new LinkedHashMap<>();
        LocalDate cursor = startDate;
        while (!cursor.isAfter(endDate)) {
            weekMap.put(cursor.with(DayOfWeek.MONDAY), Boolean.TRUE);
            cursor = cursor.plusDays(1);
        }
        return new ArrayList<>(weekMap.keySet()).stream().sorted().toList();
    }
}
