package com.intranet.util;

import com.intranet.entity.TimeSheet;
import com.intranet.entity.TimeSheetEntry;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.DayOfWeek;
import java.time.LocalDate;
import java.util.*;
import java.util.stream.Collectors;

/**
 * Shared static utilities for utilization calculations.
 * Key improvement over the original UtilizationReportingService:
 * - internalProjectIds is loaded ONCE by the caller and passed in (no per-call DB hits)
 * - No DB dependencies inside these methods
 */
public final class UtilizationCalculationUtils {

    private UtilizationCalculationUtils() {}

    // ─── Hour calculations ─────────────────────────────────────────────────────

    public static BigDecimal calculateTotalHours(List<TimeSheet> timeSheets, List<TimeSheetEntry> entries) {
        BigDecimal entryHours = entries.stream()
                .map(e -> e.getHoursWorked() != null ? e.getHoursWorked() : BigDecimal.ZERO)
                .reduce(BigDecimal.ZERO, BigDecimal::add);
        BigDecimal autoHours = timeSheets.stream()
                .filter(ts -> Boolean.TRUE.equals(ts.getAutoGenerated()))
                .map(ts -> ts.getHoursWorked() != null ? ts.getHoursWorked() : BigDecimal.ZERO)
                .reduce(BigDecimal.ZERO, BigDecimal::add);
        return entryHours.add(autoHours);
    }

    public static BigDecimal calculateBillableHours(List<TimeSheetEntry> entries) {
        return entries.stream()
                .filter(TimeSheetEntry::isBillable)
                .map(e -> e.getHoursWorked() != null ? e.getHoursWorked() : BigDecimal.ZERO)
                .reduce(BigDecimal.ZERO, BigDecimal::add);
    }

    /** Caller loads internalProjectIds once — never called per resource. */
    public static BigDecimal calculateNonBillableHours(List<TimeSheetEntry> entries,
                                                        Set<Long> internalProjectIds) {
        return entries.stream()
                .filter(e -> !e.isBillable()
                        && (e.getProjectId() == null || !internalProjectIds.contains(e.getProjectId())))
                .map(e -> e.getHoursWorked() != null ? e.getHoursWorked() : BigDecimal.ZERO)
                .reduce(BigDecimal.ZERO, BigDecimal::add);
    }

    /** Caller loads internalProjectIds once — never called per resource. */
    public static BigDecimal calculateInternalHours(List<TimeSheetEntry> entries,
                                                     Set<Long> internalProjectIds) {
        return entries.stream()
                .filter(e -> e.getProjectId() != null && internalProjectIds.contains(e.getProjectId()))
                .map(e -> e.getHoursWorked() != null ? e.getHoursWorked() : BigDecimal.ZERO)
                .reduce(BigDecimal.ZERO, BigDecimal::add);
    }

    /**
     * Planned hours = working days (excluding weekends + org holidays) × 8.
     * Holiday dates are detected from auto-generated timesheets.
     */
    public static BigDecimal calculatePlannedHours(List<TimeSheet> timeSheets,
                                                    LocalDate startDate, LocalDate endDate) {
        Set<LocalDate> holidayDates = timeSheets.stream()
                .filter(ts -> Boolean.TRUE.equals(ts.getAutoGenerated()))
                .map(TimeSheet::getWorkDate)
                .collect(Collectors.toSet());

        int workingDays = 0;
        LocalDate cursor = startDate;
        while (!cursor.isAfter(endDate)) {
            if (cursor.getDayOfWeek() != DayOfWeek.SATURDAY
                    && cursor.getDayOfWeek() != DayOfWeek.SUNDAY
                    && !holidayDates.contains(cursor)) {
                workingDays++;
            }
            cursor = cursor.plusDays(1);
        }
        return BigDecimal.valueOf(workingDays * 8L);
    }

    // ─── Derived metrics ───────────────────────────────────────────────────────

    public static BigDecimal calculateUtilizationPercentage(BigDecimal actualHours,
                                                             BigDecimal plannedHours) {
        if (plannedHours.compareTo(BigDecimal.ZERO) == 0) return BigDecimal.ZERO;
        return actualHours.multiply(BigDecimal.valueOf(100))
                .divide(plannedHours, 2, RoundingMode.HALF_UP);
    }

    public static BigDecimal calculateBillableRatio(BigDecimal billableHours, BigDecimal totalHours) {
        if (totalHours.compareTo(BigDecimal.ZERO) == 0) return BigDecimal.ZERO;
        return billableHours.multiply(BigDecimal.valueOf(100))
                .divide(totalHours, 2, RoundingMode.HALF_UP);
    }

    public static String determineUtilizationBand(double utilization,
                                                    double overThreshold, double underThreshold) {
        if (utilization >= overThreshold) return "HIGH";
        if (utilization >= 80) return "OPTIMAL";
        if (utilization >= underThreshold) return "LOW";
        return "CRITICAL";
    }

    /** Compares second half of period vs first half; returns UP/DOWN/STABLE. */
    public static String calculateTrendSignal(List<TimeSheet> timeSheets,
                                               LocalDate startDate, LocalDate endDate) {
        if (timeSheets.isEmpty()) return "STABLE";
        long totalDays = java.time.temporal.ChronoUnit.DAYS.between(startDate, endDate);
        LocalDate midPoint = startDate.plusDays(totalDays / 2);

        BigDecimal recentHours = timeSheets.stream()
                .filter(ts -> ts.getWorkDate().isAfter(midPoint))
                .map(ts -> ts.getHoursWorked() != null ? ts.getHoursWorked() : BigDecimal.ZERO)
                .reduce(BigDecimal.ZERO, BigDecimal::add);

        BigDecimal olderHours = timeSheets.stream()
                .filter(ts -> !ts.getWorkDate().isAfter(midPoint))
                .map(ts -> ts.getHoursWorked() != null ? ts.getHoursWorked() : BigDecimal.ZERO)
                .reduce(BigDecimal.ZERO, BigDecimal::add);

        BigDecimal diff = recentHours.subtract(olderHours);
        if (diff.compareTo(BigDecimal.valueOf(5)) > 0) return "UP";
        if (diff.compareTo(BigDecimal.valueOf(-5)) < 0) return "DOWN";
        return "STABLE";
    }

    public static int calculateConfidenceScore(List<TimeSheet> timeSheets) {
        if (timeSheets.isEmpty()) return 0;
        long approved = timeSheets.stream()
                .filter(ts -> ts.getStatus() == TimeSheet.Status.APPROVED)
                .count();
        return (int) ((approved * 100) / timeSheets.size());
    }

    public static int calculateApprovedDays(List<TimeSheet> timeSheets) {
        return (int) timeSheets.stream()
                .filter(ts -> ts.getStatus() == TimeSheet.Status.APPROVED)
                .count();
    }

    public static int calculateWorkingDays(LocalDate startDate, LocalDate endDate) {
        int days = 0;
        LocalDate cursor = startDate;
        while (!cursor.isAfter(endDate)) {
            if (cursor.getDayOfWeek() != DayOfWeek.SATURDAY
                    && cursor.getDayOfWeek() != DayOfWeek.SUNDAY) {
                days++;
            }
            cursor = cursor.plusDays(1);
        }
        return days;
    }

    // ─── Pattern detection ─────────────────────────────────────────────────────

    /**
     * Counts consecutive weeks (from start) where weekly utilization >= threshold.
     * Uses timesheet hoursWorked as a proxy for actual hours (no entry join needed).
     */
    public static int calculateConsecutiveWeeksOverThreshold(List<TimeSheet> timeSheets,
                                                              double threshold) {
        return countConsecutiveWeeks(timeSheets, threshold, true);
    }

    public static int calculateConsecutiveWeeksUnderThreshold(List<TimeSheet> timeSheets,
                                                               double threshold) {
        return countConsecutiveWeeks(timeSheets, threshold, false);
    }

    private static int countConsecutiveWeeks(List<TimeSheet> timeSheets, double threshold,
                                              boolean overMode) {
        if (timeSheets.isEmpty()) return 0;

        LocalDate minDate = timeSheets.stream().map(TimeSheet::getWorkDate)
                .min(Comparator.naturalOrder()).orElseThrow();
        LocalDate maxDate = timeSheets.stream().map(TimeSheet::getWorkDate)
                .max(Comparator.naturalOrder()).orElseThrow();

        Map<LocalDate, List<TimeSheet>> byWeek = timeSheets.stream()
                .collect(Collectors.groupingBy(ts -> ts.getWorkDate().with(DayOfWeek.MONDAY)));

        List<LocalDate> weeks = byWeek.keySet().stream().sorted().collect(Collectors.toList());

        int consecutive = 0;
        for (LocalDate weekStart : weeks) {
            List<TimeSheet> weekSheets = byWeek.get(weekStart);
            BigDecimal actual = weekSheets.stream()
                    .map(ts -> ts.getHoursWorked() != null ? ts.getHoursWorked() : BigDecimal.ZERO)
                    .reduce(BigDecimal.ZERO, BigDecimal::add);
            BigDecimal planned = BigDecimal.valueOf(40); // standard 5 × 8 per week
            double util = actual.multiply(BigDecimal.valueOf(100))
                    .divide(planned, 2, RoundingMode.HALF_UP).doubleValue();

            boolean meets = overMode ? util >= threshold : util <= threshold;
            if (meets) consecutive++;
            else break;
        }
        return consecutive;
    }

    public static boolean isConsistentlyOverUtilized(List<TimeSheet> timeSheets, double threshold) {
        return calculateConsecutiveWeeksOverThreshold(timeSheets, threshold) >= 4;
    }

    public static boolean isConsistentlyUnderUtilized(List<TimeSheet> timeSheets, double threshold) {
        return calculateConsecutiveWeeksUnderThreshold(timeSheets, threshold) >= 4;
    }

    // ─── Alert text generators ─────────────────────────────────────────────────

    public static List<String> buildAlertMessages(String band, boolean consistentlyOver,
                                                   boolean consistentlyUnder, String context) {
        List<String> alerts = new ArrayList<>();
        if ("CRITICAL".equals(band)) alerts.add("Critical under-utilization detected" + context);
        if ("HIGH".equals(band)) alerts.add("High utilization - risk of over-allocation" + context);
        if (consistentlyOver) alerts.add("Sustained over-utilization pattern detected" + context);
        if (consistentlyUnder) alerts.add("Sustained under-utilization pattern detected" + context);
        return alerts;
    }
}
